### ISSUE TITLE
Not working in Monterey 12.3

### ISSUE THREAD

**Issue by ismaelab** [fniephaus/alfred-homebrew#52]
Since I have updated to Monterey, I can't get the workflow to work anymore.

This is the error I receive:

`Homebrew & Cask for Alfred[[Script Filter] Queuing argument ''`
`Homebrew & Cask for Alfred[[Script Filter] Script with argv '(null)' finished`
`ERROR: Homebrew & Cask for Alfred[[Script Filter]Code 127: /bin/bash: python: command not found`

**Comment by fniephaus** [comment]
Hi @ismaelab, I'm afraid I can't look into this as I haven't upgraded to Monterey yet. Contributions are more than welcome!

**Comment by Sondho** [comment]
Python2 was uninstalled in 12.3
Try reinstalling python2.

Reference: https://www.alfredapp.com/help/kb/python-2-monterey/

**Comment by HenryQW** [comment]
> Python2 was uninstalled in 12.3 Try reinstalling python2.
> 
> Reference: https://www.alfredapp.com/help/kb/python-2-monterey/

Didn't solve the issue for me unfortunately.

**Comment by hdecoded** [comment]
I was able to get the workflow running with a workaround hope this helps 

I am basically replacing the python command with the complete location of the python command since I am unable to get the python command working globally on mac

1. Installing python 2 as suggested by @Sondho 
2. Go to the homebrew workflow and enable debug mode.
3. Trigger the brew keyword in Alfred.
4. If you are getting `Code 127: /bin/bash: python: command not found` error.
5. Open the script filter for brew and cask and change the script as follows
6. From `python brew.py "{query}"` to `/Users/<your username>/.pyenv/shims/python brew.py "{query}"`
7. Repeat for cask script filter
8. Trigger the brew or cask keyword in Alfred again
9. If you get `background.py:234 no file found` error 
10. Open the background.py file from the location shown in the error
11. Go to line 233 and replace `python` with `/Users/<your username>/.pyenv/shims/python`

**Comment by cryophobic** [comment]
Great job tracking down a solution. Followed the steps and can confirm that it is working on 12.3.1
I did have one small issue that was easily resolved. pyenv wasn't satisfied until I explicitly specified my python version. 

For some reason it defaulted to 'system' on my machine. 

I fixed it with ` pyenv global 2.7.18`

**Comment by hdecoded** [comment]
@cryophobic Gald I helped.

**Comment by kuncevic** [comment]
@Sondho Are you saying that it won't work with python3?

**Comment by kuncevic** [comment]
shall it work with python 3?

**Comment by kuncevic** [comment]
Did the solution installing python 2.7.18 with [`pyenv`](https://www.alfredapp.com/help/kb/python-2-monterey/)

Get to the step having setting the `pyenv global 2.7.18`

Now getting this error:

```
13:03:05 workflow.py:2061 DEBUG    ---------- Homebrew & Cask for Alfred (5.5.0) ----------
13:03:05 workflow.py:1468 DEBUG    reading settings from /Users/name/Library/Application Support/Alfred/Workflow Data/com.fniephaus.homebrew/settings.json
13:03:05 workflow.py:2338 INFO     checking for update ...
13:03:05 background.py:230 DEBUG    [__workflow_update_check] command cached: /Users/name/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/__workflow_update_check.argcache
13:03:05 background.py:234 DEBUG    [__workflow_update_check] passing job to background runner: [u'/usr/bin/python', '/Users/name/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.527411EF-8896-4044-88C8-08C6A94D5CF7/workflow/background.pyc', u'__workflow_update_check']
13:03:05 workflow.py:2080 ERROR    [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/name/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.527411EF-8896-4044-88C8-08C6A94D5CF7/workflow/workflow.py", line 2070, in run
    self.check_update()
  File "/Users/name/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.527411EF-8896-4044-88C8-08C6A94D5CF7/workflow/workflow.py", line 2340, in check_update
    run_in_background('__workflow_update_check', cmd)
  File "/Users/name/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.527411EF-8896-4044-88C8-08C6A94D5CF7/workflow/background.py", line 235, in run_in_background
    retcode = subprocess.call(cmd)
  File "/Users/name/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/name/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Users/name/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
13:03:05 workflow.py:2103 DEBUG    ---------- finished in 0.014s ----------
[13:03:05.472] Homebrew & Cask for Alfred[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "[Errno 2] No such file or directory",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Homebrew & Cask for Alfred'"
    }
  ]
}
```

**Comment by League2EB** [comment]
@hdecoded I get different error , how can i fix it ? 

thx all 

[![Foo](https://i.imgur.com/9tmPoyD.png)](http://google.com.au/)

**Comment by pat-s** [comment]
Avoiding screenshots might be a start 

💻😉 (sorry, the opportunity was too good)

**Comment by League2EB** [comment]
> Avoiding screenshots might be a start
> 
> 💻😉 (sorry, the opportunity was too good)

@pat-s  What does that mean?

**Comment by ahmeed83** [comment]
I followed your suggestion [hdecoded](https://github.com/hdecoded) but I'm still getting this error: 


<img width="1304" alt="Screenshot 2022-06-18 at 23 21 32" src="https://user-images.githubusercontent.com/6630503/174457392-25c889cf-1acf-484b-bf20-272359a00fdb.png">

**Comment by pat-s** [comment]
Please switch to python3, python2 is EOL and a security risk. 

Bundling a language interpreter into an application is quite unusual and comes with more challenges than keeping just the executable size small.

**Comment by Yinsen-P** [comment]
> I was able to get the workflow running with a workaround hope this helps
> 
> I am basically replacing the python command with the complete location of the python command since I am unable to get the python command working globally on mac
> 
> 1. Installing python 2 as suggested by @Sondho
> 2. Go to the homebrew workflow and enable debug mode.
> 3. Trigger the brew keyword in Alfred.
> 4. If you are getting `Code 127: /bin/bash: python: command not found` error.
> 5. Open the script filter for brew and cask and change the script as follows
> 6. From `python brew.py "{query}"` to `/Users/<your username>/.pyenv/shims/python brew.py "{query}"`
> 7. Repeat for cask script filter
> 8. Trigger the brew or cask keyword in Alfred again
> 9. If you get `background.py:234 no file found` error
> 10. Open the background.py file from the location shown in the error
> 11. Go to line 233 and replace `python` with `/Users/<your username>/.pyenv/shims/python`

I tried this solution under python 3.9 but failed. In the beginning, I can go through to step 8, but still did not solve. It did not hint step 9 ever.
Even if I installed python 2.7.18, the debug shows "[Errno 2] No such file or directory". Any help would be appreciated in advance.
Thx

**Comment by mdking117** [comment]
I'm getting an error that the module cPickle is not found.  In looking at the python code for the workflow.py file, there is a reference to cPickle.  In the workflow3.py file there is no reference cPickle.   This note is at the top of the workflow.py file, but I'm not sure which user manual I'm supposed to refer to:
"""The :class:`Workflow` object is the main interface to this library.

:class:`Workflow` is targeted at Alfred 2. Use
:class:`~workflow.Workflow3` if you want to use Alfred 3's new
features, such as :ref:`workflow variables <workflow-variables>` or
more powerful modifiers.

See :ref:`setup` in the :ref:`user-manual` for an example of how to set
up your Python script to best utilise the :class:`Workflow` object.

Can someone point me to the right material?

**Comment by wookayin** [comment]
Regarding Line 9: "background.py:234 no file found error"

One can completely disable the run_in_background because there is no point of updating the workflow (actually should not run autoupdate) if it's unmaintained and users need to make a local patch to make this workflow with goddamn python 2.

```diff
     # Call this script
     cmd = ['/usr/bin/python', __file__, name]
     _log().debug('[%s] passing job to background runner: %r', name, cmd)

-    retcode = subprocess.call(cmd)
+    try:
+        retcode = subprocess.call(cmd)
+    except:
+        retcode = None

     if retcode:  # pragma: no cover
         _log().error('[%s] background runner failed with %d', name, retcode)
     else:
         _log().debug('[%s] background job started', name)

```

**Comment by marcelluiz96** [comment]
Adding to the solution from @hdecoded (which worked out great, thank you!)
Specifying python 2 for the scripts of that workflow alone might save one from having to set them as the global python version (assuming you're using pyenv):

/Users/<<your-username>>/.pyenv/shims/python2
